%21103192 Sanchit jain%
clear all;
close all;
clc;
display('Half Adder');
display('_________________');
display('     A     B     S     C');
A = [0 0 1 1];
B = [0 1 0 1];
S = XOR(A,B);
C= A&B;
display([transpose(A) transpose(B) transpose(S) transpose(C)]);
display('Full Adder');
display('________________');
A=[0 0 0 0 1 1 1 1];
B=[0 0 1 1 0 0 1 1];
Cin=[0 1 0 1 0 1 0 1];
S=XOR(XOR(A,B),Cin);
C=XOR(A,B)&Cin + A&B;
display('     A     B     Cin     S    C');
display([transpose(A) transpose(B) transpose(Cin) transpose(S) transpose(C)]);
display('half Subtractor');
display('_________________');
A = [0 0 1 1];
B = [0 1 0 1];
D= XOR(A,B);
Bout= ~A&B;
display('     A     B     D     Bout');
display([transpose(A) transpose(B) transpose(D) transpose(Bout)]);
display('Full Subtractor');
display('__________________');
A=[0 0 0 0 1 1 1 1];
B=[0 0 1 1 0 0 1 1];
Bin=[0 1 0 1 0 1 0 1];
D=XOR(XOR(A,B),Bin);
Bout=(~A&B)+(~(XOR(A,B))&Bin);
display('     A     B     Bin     D    Bout');
display([transpose(A) transpose(B) transpose(Bin) transpose(D) transpose(Bout)]);
display('Full Adder using half adder');
display('____________________________');
A=[0 0 0 0 1 1 1 1];
B=[0 0 1 1 0 0 1 1];
Cin=[0 1 0 1 0 1 0 1];
[X1,C1]=HA(A,B);
[X2,C2]=HA(X1,Cin);
Cout=C1+C2;
display('     A     B     Cin     S    Cout');
display([transpose(A) transpose(B) transpose(Cin) transpose(X2) transpose(Cout)]);
display('Full Subtractor using half Subtractor');
display('____________________________');
A=[0 0 0 0 1 1 1 1];
B=[0 0 1 1 0 0 1 1];
Bin=[0 1 0 1 0 1 0 1];
[X1,B1]=HS(A,B);
[D,B2]=HS(X1,Bin);
Bout=B1+B2;
display('     A     B     Bin     D    Bout');
display([transpose(A) transpose(B) transpose(Bin) transpose(D) transpose(Bout)]);

